### PR TITLE
Enable to extend util

### PR DESCRIPTION
**Pull request by hiramatsutaku**
@alan-cooney 
Thank you for the nice package 👍 
I am using it comfortably.

By the way, I'm using an RDS resolver, so I wanted to extend util.
So I sent this PR. 
Please check when you have time

### CODE REVIEW

**Comment by alan-cooney** [comment]
Thanks for the PR @hiramatsutaku - makes sense. 

This makes sense for making the module extendable. However if you have some implementations of the underlying RDS utils that would be even better - we could simply make a copy of e.g. https://github.com/skyhookadventure/appsync-template-tester/blob/main/src/util-dynamodb.ts and add in any you have (fine if it's an incomplete list for now).

Let me know what you think - otherwise I'm happy to merge this in.

**Comment by hiramatsutaku** [comment]
@alan-cooney 
Thanks for the quick reply 😄 

>This makes sense for making the module extendable. 

Yes.

>However if you have some implementations of the underlying RDS utils that would be even better

I think so, but the cost of preparing the following serialized SQL result（`$ctx.result`）for each test is high for me.

SQL
```
SELECT id FROM todos;
```

serialized SQL result
```
"{\"sqlStatementResults\":[{\"columnMetadata\":[{\"arrayBaseColumnType\":0,\"isAutoIncrement\":true,\"isCaseSensitive\":false,\"isCurrency\":false,\"isSigned\":true,\"label\":\"id\",\"name\":\"id\",\"nullable\":0,\"precision\":10,\"scale\":0,\"schemaName\":\"\",\"tableName\":\"todos\",\"type\":4,\"typeName\":\"INT\",\"signed\":true,\"autoIncrement\":true,\"caseSensitive\":false,\"currency\":false}],\"numberOfRecordsUpdated\":0,\"records\":[[{\"longValue\":1}],[{\"longValue\":2}]]}]}
```

So I would like to have this pull request merged and then add the RDS resolver's util in another pull request.

**Comment by alan-cooney** [comment]
Thanks for the PR - I've merged it. 

One small additional issue is that this is causing downstream errors in tests from some of our services that depend on this (they kick off new tests whenever a dependency is updated):

```typescript
  result?: object | string;
```

Are you happy for me to revert the result type to just object - it seems like you're using it that way as well anyway?

**Comment by hiramatsutaku** [comment]
@alan-cooney 
Thanks for the quick merge.

>Are you happy for me to revert the result type to just object - it seems like you're using it that way as well anyway?

I want to use the result type as string.
How about making the Context type extensible?（If so, the default result type can be object.）

**Pull request merged**
